[package]
name = "rust_websocket"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tungstenite = "0.27.0"
mlua = { version = "0.11.2", features = ["lua53","module"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "1.0.0-alpha.1"
